# NEWS API Ingestion (Dynamic)

### Pre Run Activity
- Make sure to tap the 3 dot icon on top left and enable the necessary 'External Access' integrations for the notebook.
- Update the 'news_config.json' with the requirement before starting the run.

## Runtime Config Set-Up

In [2]:
GLOBAL_CONFIG_PATH = "news_config.json"

### Importing Libraries

In [4]:
import requests
import json
import pandas as pd
from datetime import date, timedelta, datetime
import math
import warnings
from bs4 import BeautifulSoup
import time
import random
import snowflake.connector
from urllib.parse import urlparse
import hashlib
from snowflake.connector.pandas_tools import write_pandas

### Auto Run-Name Initiationa Code

In [5]:
def get_config(CONFIG_PATH="news_config.json"):
    with open(CONFIG_PATH) as f:
        config = json.load(f)
    return config
config = get_config(GLOBAL_CONFIG_PATH) #DEBUG

GLOBAL_RUN_NAME = config['run_auto_pickup']

### Testing Endpoint

In [6]:
resp = requests.get('https://newsapi.org/v2/everything?q=apple&to=2025-09-10&from=2025-09-10&apiKey=c494f280427646c78473013990b3cd45')
len(resp.json())

3

## Main Code

In [7]:
def get_config_run(run_name):
    config = get_config()
    config_run = next((r for r in config['runs'] if r['run_name'] == run_name), None)
    return config_run

def get_config_snowflake():
    config = get_config()
    config_snowflake = config["snowflake"]
    return config_snowflake

def get_snowlfake_conn(schema_name):
    config_snowflake = get_config_snowflake()
    conn = snowflake.connector.connect(
        user=config_snowflake["user"],
        password=config_snowflake["password"],
        account=config_snowflake["account"],
        warehouse=config_snowflake["warehouse"],
        database=config_snowflake["database"],
        schema=schema_name # SQL Specific
    )
    return conn
    
config = get_config() #DEBUG
config_run = get_config_run(GLOBAL_RUN_NAME)
config_snowflake = get_config_snowflake()
print(config, config_run, config_snowflake)

{'run_auto_pickup': 'OracleScheduled', 'news_api_key_auto_pickup': 'news_api_key_2', 'runs': [{'run_name': 'OracleAllowed', 'entity_name': 'Oracle', 'q': 'oracle', 'from_days_ago': 25, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'}, {'run_name': 'OracleHistorical', 'entity_name': 'Oracle', 'q': 'oracle', 'from_days_ago': 1825, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'}, {'run_name': 'OracleScheduled', 'entity_name': 'Oracle', 'q': 'oracle', 'from_days_ago': 30, 'till_days': 0, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'}, {'run_name': 'PalantirAllowed', 'entity_name': 'Palantir', 'q': 'palantir', 'from_days_ago': 25, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'}, {'run_name': 'PalantirHistorical', 'entity_name': 'Palantir', 'q': 'palantir', 'from_days_ago': 1825, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'}, {'run_name': 'PalantirScheduled', 'entity_name': 'Palantir', 'q': 'palantir', 'from_days_ago': 7, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'}], 'news_api_key_list': {'news_api_key_1': 'c494f280427646c78473013990b3cd45', 'news_api_key_2': 'f20a04b3e9f54ef392a46c831917804b'}, 'snowflake': {'account': 'CYWCXZB-EPC46775', 'user': 'ARAVINDSURESH03', 'password': 'Abirami38Aravind!', 'role': 'ACCOUNTADMIN', 'warehouse': 'COMPUTE_WH', 'database': 'SIGNAL_EXTRACTION_DB', 'schema': '<CODE>'}} {'run_name': 'OracleScheduled', 'entity_name': 'Oracle', 'q': 'oracle', 'from_days_ago': 30, 'till_days': 0, 'endpoint': 'https://newsapi.org/v2/everything', 'language': 'en', 'sortBy': 'publishedAt', 'page': '<CODE>', 'searchIn': '<CODE>'} {'account': 'CYWCXZB-EPC46775', 'user': 'ARAVINDSURESH03', 'password': 'Abirami38Aravind!', 'role': 'ACCOUNTADMIN', 'warehouse': 'COMPUTE_WH', 'database': 'SIGNAL_EXTRACTION_DB', 'schema': '<CODE>'}

In [8]:
def create_url_string(config_run, config):
    # calc_to = date.today() #This part will get auto-optimised when set to recurring.
    calc_to = date.today() + timedelta(days=config_run["till_days"]) #If negative then the range will reduce.
    calc_from = calc_to - timedelta(days=config_run["from_days_ago"])
    calc_from = calc_from.isoformat()
    
    url_string = f"""
        {config_run["endpoint"]}?
        q={config_run["q"]}&
        language={config_run["language"]}&
        to={calc_to}&
        from={calc_from}&
        sortBy={config_run["sortBy"]}&
        apiKey={config["news_api_key_list"][config["news_api_key_auto_pickup"]]}
    """
    url_string = url_string.replace(' ', '').replace('\n', '')
    return url_string

config_run = get_config_run(GLOBAL_RUN_NAME) 
url_string = create_url_string(config_run, config)
print(url_string)

https://newsapi.org/v2/everything?q=oracle&language=en&to=2025-10-29&from=2025-09-29&sortBy=publishedAt&apiKey=f20a04b3e9f54ef392a46c831917804b

In [9]:
def fetch_news(url_string):
    """
    Fetches news, makes sures all the pages are scraped
    """
    response = requests.get(url_string, params = {"page": 1})
    data = response.json()

    total_results = data.get("totalResults", 0)
    articles_data = data.get("articles", [])
    # print(f'total_results: {total_results} | articles_data: {articles_data}')
    
    print(f"Total Results: {total_results}")
    if total_results == 0:
        raise Exception("Exception: No articles captured in current run.")
        return articles_data
        
    if total_results > 100:
        total_pages = math.ceil(total_results / 100)
        for page in range(2, total_pages+1):
            print(f'Going through page {page}/{total_pages}')
            response = requests.get(url_string, params = {"page": page})
            data = response.json()
            
            page_articles = data.get("articles")
            if page_articles is not None: # Avoids Nonetype Object error
                articles_data.extend(page_articles)
            # print(page_articles)
            
    if len(articles_data) != total_results:
        warnings.warn(f'Article Count Mismatch" {len(articles_data)}|{total_results}')

    print(f'No. of Articles: {len(articles_data)}')
    return articles_data

print(url_string)
articles_data = fetch_news(url_string)
print(articles_data)

https://newsapi.org/v2/everything?q=oracle&language=en&to=2025-10-29&from=2025-09-29&sortBy=publishedAt&apiKey=f20a04b3e9f54ef392a46c831917804b
Total Results: 2631
Going through page 2/27
Going through page 3/27
Going through page 4/27
Going through page 5/27
Going through page 6/27
Going through page 7/27
Going through page 8/27
Going through page 9/27
Going through page 10/27
Going through page 11/27
Going through page 12/27
Going through page 13/27
Going through page 14/27
Going through page 15/27
Going through page 16/27
Going through page 17/27
Going through page 18/27
Going through page 19/27
Going through page 20/27
Going through page 21/27
Going through page 22/27
Going through page 23/27
Going through page 24/27
Going through page 25/27
Going through page 26/27
Going through page 27/27
No. of Articles: 496

C:\Users\aravi\AppData\Local\Temp\ipykernel_23128\2764801540.py:30: UserWarning: Article Count Mismatch" 496|2631
  warnings.warn(f'Article Count Mismatch" {len(articles_data)}|{total_results}')

In [10]:
def articles_to_df(articles_data):
    def get_domain(url: str) -> str:
        """Extract domain from URL (finance.yahoo.com, etc.)."""
        if not url or pd.isna(url):
            return None
        parsed = urlparse(url)
        return parsed.netloc.lower()

    # Main
    df = pd.json_normalize(articles_data, sep="_") #Flatten and separate by
    column_rename_mapping = {
        "urlToImage": "url_to_image",
        "publishedAt": "published_at_utc",
        "content": "content_truncated"
    }
    df = df.rename(columns=column_rename_mapping)
    df["url_domain"] = df["url"].apply(get_domain)
    df["published_at_utc"] = pd.to_datetime(df["published_at_utc"], utc=True).dt.tz_localize(None)
    return df

df = articles_to_df(articles_data)
df.head(3)

,author,title,description,url,url_to_image,published_at_utc,content_truncated,source_id,source_name,url_domain
0,benzinga.com,Oracle Unveils Digital Assets Platform To Powe...,Oracle Corp (NYSE:ORCL) announced plans to lau...,https://biztoc.com/x/351b2b78fb9ac1ff,https://biztoc.com/cdn/351b2b78fb9ac1ff_s.webp,2025-10-28 16:20:33,Oracle Corp (NYSE:ORCL) announced plans to lau...,None,Biztoc.com,biztoc.com
1,info@thehackernews.com (The Hacker News),Researchers Expose GhostCall and GhostHire: Bl...,Threat actors tied to North Korea have been ob...,https://thehackernews.com/2025/10/researchers-...,https://blogger.googleusercontent.com/img/b/R2...,2025-10-28 16:12:00,Threat actors tied to North Korea have been ob...,None,Internet,thehackernews.com
2,Business Wire,Hexagon and Management Controls Deliver Real-T...,New integration advances digital project contr...,https://financialpost.com/pmn/business-wire-ne...,None,2025-10-28 16:07:04,New integration advances digital project contr...,financial-post,Financial Post,financialpost.com

In [ ]:
# def test_ensure_network_rule_for_domain(
#     df, 
#     nr_name = "news_domains_nr", 
#     integration_name = "news_domains_integration",
#     schema = "UTILS"):
#     """
#     Create or replace a single Snowflake network rule that covers all given domains.
#     Attach it to the API integration.
#     """
#     conn = get_snowlfake_conn(schema_name=schema)
#     cur = conn.cursor() #Start

#     cur.execute(f"DESCRIBE NETWORK RULE SIGNAL_EXTRACTION_DB.{schema}.{nr_name}") #Hard Coded and saved in utils schema.
#     desc_rows = cur.fetchall()
#     desc_list = list(desc_rows[0])
    
#     for idx, val in enumerate(desc_list):
#         if ".com" in str(val).lower():
#             value_list_str_existing = val.lower()
#     print(value_list_str_existing)
            
#     value_list_existing = [d.strip().strip("'").lower() for d in value_list_str_existing.split(",")]
#     value_list_latest = [i.lower() for i in list(df['url_domain'].unique())]
#     value_list_optimised = list(set(value_list_existing + value_list_latest))
#     value_list_str_optimised = ", ".join([f"'{d}'" for d in value_list_optimised])
#     print(f'Existing Value List ({len(value_list_existing)}): {value_list_existing}')
#     print(f'Latest Value List ({len(value_list_latest)}): {value_list_latest}')
#     print(f'Optimised Value List ({len(value_list_optimised)}): {value_list_optimised}')
#     print(f'NR String: {value_list_str_optimised}')

#     # Network Rule SQL
#     create_sql = f"""
#     CREATE OR REPLACE NETWORK RULE {nr_name}
#         TYPE = HOST_PORT
#         MODE = EGRESS
#         VALUE_LIST = ({value_list_str_optimised});
#     """
#     cur.execute(create_sql)
    
#     # Collect all network rules and re-attach to integration (Both alter & replace sql are having caching issues on re-attaching)
#     alter_sql = f"""
#     ALTER EXTERNAL ACCESS INTEGRATION {integration_name}
#         SET ALLOWED_NETWORK_RULES = ({nr_name})
#         ENABLED = TRUE;
#     """
#     # create or replace sql
#     replace_sql = f"""
#     CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION {integration_name}
#         ALLOWED_NETWORK_RULES = (
#             {nr_name}
#         )
#         ENABLED = TRUE;
#     """
    
#     # cur.execute(replace_sql)
#     cur.execute(alter_sql)
#     cur.close() #End
    
#     print(f"Network rule ({nr_name}) updated in Integration ({integration_name})")

# test_ensure_network_rule_for_domain(df)

In [11]:
def scrape_url_helper(url):
    try:
        response = requests.get(url, timeout=10)
        # if response.status_code != 200:
        #     return None, 0
            
        soup = BeautifulSoup(response.text, 'html.parser')

        # title = soup.title.string.strip() if soup.title else "" # Extract title
        paragraphs = [p.get_text(strip=True) for p in soup.find_all('p')] # Extract all paragraph text
        content = " ".join(paragraphs)
        
        # paragraphs = soup.find_all("p") #[GPT Method] Keeps formatting intact (other method, removes additional newlines and spaces)
        # content = " ".join([p.get_text() for p in paragraphs if p.get_text()])
        # content = content.strip()
        print(f'{url} - content')
        return content, len(content)
    except requests.exceptions.Timeout as e:
        # Handle connection timeout specifically
        print(f"TIMEOUT for url {url}: {e}")
        return None, -2
    except Exception as e:
        # If error (broken link, paywall, etc.)
        print(f"ERROR for url {url}: {type(e).__name__} — {e}")
        return None, -1 #(-1 to indicate that domain network rule not created)

def scrape_url(df, chunk_size, delay_between_chunks):
    df['content_full'] = None
    df['content_size'] = 0
    df_len = len(df)

    for idx, row in df.iterrows():
        rand_delay_between_chunks = random.uniform(0.5, 1)
        url = row.get('url')
        if not url:
            continue
        content_full, content_size = scrape_url_helper(url)
        print(f'{idx+1}/{df_len} | Scraped url({content_size}): {url}')
        df.at[idx, 'content_full'] = content_full
        df.at[idx, 'content_size'] = content_size
        if idx%chunk_size == 0:
            print(f'{idx+1}/{df_len} | Sleeping for {rand_delay_between_chunks}s')
            time.sleep(rand_delay_between_chunks)
    return df
    

df = scrape_url(df, chunk_size=10, delay_between_chunks=3)
df.head(20)

https://biztoc.com/x/351b2b78fb9ac1ff - content
1/496 | Scraped url(288): https://biztoc.com/x/351b2b78fb9ac1ff
1/496 | Sleeping for 0.5524814252959431s
https://thehackernews.com/2025/10/researchers-expose-ghostcall-and.html - content
2/496 | Scraped url(7616): https://thehackernews.com/2025/10/researchers-expose-ghostcall-and.html
https://financialpost.com/pmn/business-wire-news-releases-pmn/hexagon-and-management-controls-deliver-real-time-contractor-cost-reporting-with-launch-of-ecosys-mytrack-connector - content
3/496 | Scraped url(0): https://financialpost.com/pmn/business-wire-news-releases-pmn/hexagon-and-management-controls-deliver-real-time-contractor-cost-reporting-with-launch-of-ecosys-mytrack-connector
https://finance.yahoo.com/news/jim-cramer-says-nvidia-most-160255087.html - content
4/496 | Scraped url(0): https://finance.yahoo.com/news/jim-cramer-says-nvidia-most-160255087.html
https://pitchfork.com/news/animal-collective-geologist-announces-debut-solo-album-shares-new-video-watch/ - content
5/496 | Scraped url(2403): https://pitchfork.com/news/animal-collective-geologist-announces-debut-solo-album-shares-new-video-watch/
http://electrek.co/2025/10/28/elon-musk-not-leaving-tesla-threat-blackmail/ - content
6/496 | Scraped url(6994): http://electrek.co/2025/10/28/elon-musk-not-leaving-tesla-threat-blackmail/
https://www.macworld.com/article/2949071/virtualbox-review.html - content
7/496 | Scraped url(7346): https://www.macworld.com/article/2949071/virtualbox-review.html
https://finance.yahoo.com/news/microsoft-to-report-q1-earnings-following-new-openai-deal-151933845.html - content
8/496 | Scraped url(0): https://finance.yahoo.com/news/microsoft-to-report-q1-earnings-following-new-openai-deal-151933845.html
https://finance.yahoo.com/news/big-tech-has-to-walk-the-line-with-ai-spending-this-earnings-season-151904142.html - content
9/496 | Scraped url(0): https://finance.yahoo.com/news/big-tech-has-to-walk-the-line-with-ai-spending-this-earnings-season-151904142.html
https://www.forbes.com/sites/danrunkevicius/2025/10/28/ai-is-more-than-stock-market-its--economic-stimulus/ - content
10/496 | Scraped url(2872): https://www.forbes.com/sites/danrunkevicius/2025/10/28/ai-is-more-than-stock-market-its--economic-stimulus/
https://biztoc.com/x/5093f82c166a71e3 - content
11/496 | Scraped url(280): https://biztoc.com/x/5093f82c166a71e3
11/496 | Sleeping for 0.8100182659061763s
https://www.thestreet.com/markets/stock-market-today-stocks-jump-as-fed-meeting-kicks-off - content
12/496 | Scraped url(43): https://www.thestreet.com/markets/stock-market-today-stocks-jump-as-fed-meeting-kicks-off
https://www.motherjones.com/politics/2025/10/bari-weiss-cbs-news-david-ellison-larry-ellison-artificial-intelligence-ai-60-minutes/ - content
13/496 | Scraped url(14250): https://www.motherjones.com/politics/2025/10/bari-weiss-cbs-news-david-ellison-larry-ellison-artificial-intelligence-ai-60-minutes/
https://biztoc.com/x/0df2ec0da4a4f484 - content
14/496 | Scraped url(289): https://biztoc.com/x/0df2ec0da4a4f484
http://www.st.ryukoku.ac.jp/~kjm/security/memo/2025/10.html#20251029__nexperia - content
15/496 | Scraped url(23495): http://www.st.ryukoku.ac.jp/~kjm/security/memo/2025/10.html#20251029__nexperia
https://biztoc.com/x/616afdeaea9d0199 - content
16/496 | Scraped url(284): https://biztoc.com/x/616afdeaea9d0199
https://finance.yahoo.com/news/wedbush-raises-pt-advanced-micro-144650464.html - content
17/496 | Scraped url(0): https://finance.yahoo.com/news/wedbush-raises-pt-advanced-micro-144650464.html
https://finance.yahoo.com/news/monness-maintains-neutral-stance-oracle-144647356.html - content
18/496 | Scraped url(0): https://finance.yahoo.com/news/monness-maintains-neutral-stance-oracle-144647356.html
https://www.thestreet.com/investing/stocks/analysts-revamp-oracle-stock-forecast-with-new-financial-model - content
19/496 | Scraped url(43): https://www.thestreet.com/investing/stocks/analysts-revamp-oracle-stock-forecast-with-new-financial-model
https://www.businessinsider.com/10-richest-people-ai-boom-tech-wealth-musk-ellison-zuck-2025-10 - content
20/496 | Scraped url(2646): https://www.businessinsider.com/10-richest-people-ai-boom-tech-wealth-musk-ellison-zuck-2025-10
https://finance.yahoo.com/video/microsofts-27-openai-stake-means-143402876.html - content
21/496 | Scraped url(0): https://finance.yahoo.com/video/microsofts-27-openai-stake-means-143402876.html
21/496 | Sleeping for 0.8139765540870592s
https://biztoc.com/x/d66b3418cf3c0edc - content
22/496 | Scraped url(282): https://biztoc.com/x/d66b3418cf3c0edc
https://cointelegraph.com/news/how-to-turn-chatgpt-into-your-personal-crypto-trading-assistant - content
23/496 | Scraped url(0): https://cointelegraph.com/news/how-to-turn-chatgpt-into-your-personal-crypto-trading-assistant
https://thefly.com/permalinks/entry.php/id4222747/ORCL-Oracle-announces-Digital-Assets-Data-Nexus-for-banks - content
24/496 | Scraped url(569): https://thefly.com/permalinks/entry.php/id4222747/ORCL-Oracle-announces-Digital-Assets-Data-Nexus-for-banks
https://techxplore.com/news/2025-10-amazon-lay-corporate-employees.html - content
25/496 | Scraped url(129): https://techxplore.com/news/2025-10-amazon-lay-corporate-employees.html
https://www.globenewswire.com/news-release/2025/10/28/3175589/0/en/Mutuum-Finance-MUTM-Reveals-Core-Components-for-V1-Lending-Protocol-as-It-Attracts-Over-17-500-Holders.html - content
26/496 | Scraped url(8154): https://www.globenewswire.com/news-release/2025/10/28/3175589/0/en/Mutuum-Finance-MUTM-Reveals-Core-Components-for-V1-Lending-Protocol-as-It-Attracts-Over-17-500-Holders.html
https://www.infoq.com/news/2025/10/java-news-roundup-oct20-2025/ - content
27/496 | Scraped url(7947): https://www.infoq.com/news/2025/10/java-news-roundup-oct20-2025/
https://biztoc.com/x/a71e6788828050b5 - content
28/496 | Scraped url(283): https://biztoc.com/x/a71e6788828050b5
https://biztoc.com/x/48b13ae112336c85 - content
29/496 | Scraped url(282): https://biztoc.com/x/48b13ae112336c85
https://lwn.net/Articles/1043776/ - content
30/496 | Scraped url(147): https://lwn.net/Articles/1043776/
https://biztoc.com/x/4fbc61618aa5eccd - content
31/496 | Scraped url(287): https://biztoc.com/x/4fbc61618aa5eccd
31/496 | Sleeping for 0.8762693738727103s
https://finance.yahoo.com/news/terminator-governor-now-billionaire-friendship-123108103.html - content
32/496 | Scraped url(0): https://finance.yahoo.com/news/terminator-governor-now-billionaire-friendship-123108103.html
https://biztoc.com/x/054af715c60441f4 - content
33/496 | Scraped url(289): https://biztoc.com/x/054af715c60441f4
https://theconversation.com/ai-chatbots-are-becoming-everyday-tools-for-mundane-tasks-use-data-shows-266670 - content
34/496 | Scraped url(5350): https://theconversation.com/ai-chatbots-are-becoming-everyday-tools-for-mundane-tasks-use-data-shows-266670
https://biztoc.com/x/fef9070200cd5081 - content
35/496 | Scraped url(0): https://biztoc.com/x/fef9070200cd5081
https://www.investopedia.com/5-things-to-know-before-the-stock-market-opens-october-28-2025-11838298 - content
36/496 | Scraped url(0): https://www.investopedia.com/5-things-to-know-before-the-stock-market-opens-october-28-2025-11838298
https://finance.yahoo.com/news/ubs-reiterates-buy-oracle-orcl-121408351.html - content
37/496 | Scraped url(0): https://finance.yahoo.com/news/ubs-reiterates-buy-oracle-orcl-121408351.html
https://www.channelnewsasia.com/business/oracle-says-there-real-value-in-ai-demand-far-outpaces-supply-5429936 - content
38/496 | Scraped url(1106): https://www.channelnewsasia.com/business/oracle-says-there-real-value-in-ai-demand-far-outpaces-supply-5429936
https://biztoc.com/x/caaf11027fa1d3fd - content
39/496 | Scraped url(284): https://biztoc.com/x/caaf11027fa1d3fd
https://biztoc.com/x/e17aa552fb16136a - content
40/496 | Scraped url(0): https://biztoc.com/x/e17aa552fb16136a
https://finance.yahoo.com/news/oracle-reaches-hyperscaler-heights-300-104606841.html - content
41/496 | Scraped url(0): https://finance.yahoo.com/news/oracle-reaches-hyperscaler-heights-300-104606841.html
41/496 | Sleeping for 0.8027251079744894s
https://www.hospitalitynet.org/opinion/4129512.html - content
42/496 | Scraped url(7372): https://www.hospitalitynet.org/opinion/4129512.html
https://www.forbes.com/sites/zinnialee/2025/10/28/taiwans-foxconn-to-invest-up-to-14-billion-in-ai-data-center-equipment/ - content
43/496 | Scraped url(1923): https://www.forbes.com/sites/zinnialee/2025/10/28/taiwans-foxconn-to-invest-up-to-14-billion-in-ai-data-center-equipment/
https://www.forbes.com/sites/tylerroush/2025/10/28/2025s-incredible-ai-spending-frenzy-latest-us-forms-1-billion-partnership-with-amd-list/ - content
44/496 | Scraped url(7528): https://www.forbes.com/sites/tylerroush/2025/10/28/2025s-incredible-ai-spending-frenzy-latest-us-forms-1-billion-partnership-with-amd-list/
https://www.forbes.com/sites/jeffreymarcus/2025/10/28/ai-boom-or-ai-bubble/ - content
45/496 | Scraped url(3627): https://www.forbes.com/sites/jeffreymarcus/2025/10/28/ai-boom-or-ai-bubble/
https://coinjournal.net/news/chainlink-expands-into-240b-property-tokenization-with-balcony-check-price-forecast/ - content
46/496 | Scraped url(5753): https://coinjournal.net/news/chainlink-expands-into-240b-property-tokenization-with-balcony-check-price-forecast/
https://pypi.org/project/openfold3/ - content
47/496 | Scraped url(36): https://pypi.org/project/openfold3/
https://www.globenewswire.com/news-release/2025/10/28/3175135/0/en/HAUST-Network-Mainnet-Goes-Live-in-Impressive-Launch.html - content
48/496 | Scraped url(5830): https://www.globenewswire.com/news-release/2025/10/28/3175135/0/en/HAUST-Network-Mainnet-Goes-Live-in-Impressive-Launch.html
https://biztoc.com/x/1faff857e227934d - content
49/496 | Scraped url(275): https://biztoc.com/x/1faff857e227934d
https://www.theregister.com/2025/10/28/ibm_end_of_marketing_vmware_cloud/ - content
50/496 | Scraped url(0): https://www.theregister.com/2025/10/28/ibm_end_of_marketing_vmware_cloud/
https://www.madshrimps.be/news/amd-secures-1b-u-s-energy-department-contract-for-lux-and-discovery-supercomputers/ - content
51/496 | Scraped url(1577): https://www.madshrimps.be/news/amd-secures-1b-u-s-energy-department-contract-for-lux-and-discovery-supercomputers/
51/496 | Sleeping for 0.6723979141857933s
https://www.cnbc.com/2025/10/28/google-nextera-iowa-duane-arnold-nuclear-power-plant-ai-energy-demand-data-centers.html - content
52/496 | Scraped url(160): https://www.cnbc.com/2025/10/28/google-nextera-iowa-duane-arnold-nuclear-power-plant-ai-energy-demand-data-centers.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017481_AD_1.html - content
53/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017481_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017479_AD_1.html - content
54/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017479_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017478_AD_1.html - content
55/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017478_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017477_AD_1.html - content
56/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017477_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017476_AD_1.html - content
57/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017476_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017475_AD_1.html - content
58/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017475_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017474_AD_1.html - content
59/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017474_AD_1.html
http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017471_AD_1.html - content
60/496 | Scraped url(0): http://vrda.jpcert.or.jp/feed/ja/JVNiPedia_JVNDB-2025-017471_AD_1.html
https://economictimes.indiatimes.com/tech/artificial-intelligence/big-tech-to-report-earnings-under-specter-of-ai-bubble/articleshow/124863981.cms - content
61/496 | Scraped url(358): https://economictimes.indiatimes.com/tech/artificial-intelligence/big-tech-to-report-earnings-under-specter-of-ai-bubble/articleshow/124863981.cms
61/496 | Sleeping for 0.738606806590509s
https://biztoc.com/x/bf5e3a43ada1937b - content
62/496 | Scraped url(285): https://biztoc.com/x/bf5e3a43ada1937b
https://www.bostonherald.com/2025/10/27/explore-hyrules-finest-adventures-in-the-best-zelda-games/ - content
63/496 | Scraped url(5531): https://www.bostonherald.com/2025/10/27/explore-hyrules-finest-adventures-in-the-best-zelda-games/
https://pypi.org/project/iflow-mcp-mcp-server-jysd-cx-oracle/1.0.1/ - content
64/496 | Scraped url(36): https://pypi.org/project/iflow-mcp-mcp-server-jysd-cx-oracle/1.0.1/
https://pypi.org/project/iflow-mcp-mcp-server-jysd-cx-oracle/ - content
65/496 | Scraped url(36): https://pypi.org/project/iflow-mcp-mcp-server-jysd-cx-oracle/
https://financialpost.com/globe-newswire/streamex-corp-nasdaq-stex-enters-strategic-partnership-with-chainlink-as-its-official-oracle-provider-to-strengthen-tokenization-infrastructure - content
66/496 | Scraped url(0): https://financialpost.com/globe-newswire/streamex-corp-nasdaq-stex-enters-strategic-partnership-with-chainlink-as-its-official-oracle-provider-to-strengthen-tokenization-infrastructure
https://www.globenewswire.com/news-release/2025/10/28/3175062/22558/en/Streamex-Corp-NASDAQ-STEX-Enters-Strategic-Partnership-with-Chainlink-as-Its-Official-Oracle-Provider-to-Strengthen-Tokenization-Infrastructure.html - content
67/496 | Scraped url(6226): https://www.globenewswire.com/news-release/2025/10/28/3175062/22558/en/Streamex-Corp-NASDAQ-STEX-Enters-Strategic-Partnership-with-Chainlink-as-Its-Official-Oracle-Provider-to-Strengthen-Tokenization-Infrastructure.html
https://www.cnet.com/news/social-media/tiktoks-fate-may-be-decided-this-week-after-years-of-threats-and-bans/ - content
68/496 | Scraped url(4023): https://www.cnet.com/news/social-media/tiktoks-fate-may-be-decided-this-week-after-years-of-threats-and-bans/
https://www.techradar.com/pro/live/adobe-max-la-2025 - content
69/496 | Scraped url(5713): https://www.techradar.com/pro/live/adobe-max-la-2025
https://siliconangle.com/2025/10/27/amd-hpe-build-two-new-supercomputers-energy-department/ - content
70/496 | Scraped url(5318): https://siliconangle.com/2025/10/27/amd-hpe-build-two-new-supercomputers-energy-department/
https://www.cnbc.com/2025/10/27/jim-cramer-jpmorgan-trillion-market-cap.html - content
71/496 | Scraped url(160): https://www.cnbc.com/2025/10/27/jim-cramer-jpmorgan-trillion-market-cap.html
71/496 | Sleeping for 0.5544124272399592s
https://www.theverge.com/news/807483/amd-department-of-energy-announce-1-billion-ai-supercomputer-partnership - content
72/496 | Scraped url(0): https://www.theverge.com/news/807483/amd-department-of-energy-announce-1-billion-ai-supercomputer-partnership
https://cointelegraph.com/news/dydx-governance-community-vote-proposal-outage - content
73/496 | Scraped url(0): https://cointelegraph.com/news/dydx-governance-community-vote-proposal-outage
https://nypost.com/2025/10/27/business/paramount-skydance-to-slash-1000-jobs-this-week-in-first-wave-of-mass-layoffs/ - content
74/496 | Scraped url(2331): https://nypost.com/2025/10/27/business/paramount-skydance-to-slash-1000-jobs-this-week-in-first-wave-of-mass-layoffs/
https://bitcoinist.com/whales-double-down-chainlink-188m-moved-off-binance/ - content
75/496 | Scraped url(6931): https://bitcoinist.com/whales-double-down-chainlink-188m-moved-off-binance/
https://financialpost.com/pmn/business-pmn/amds-ai-chips-to-power-supercomputers-at-energy-department-lab - content
76/496 | Scraped url(0): https://financialpost.com/pmn/business-pmn/amds-ai-chips-to-power-supercomputers-at-energy-department-lab
https://variety.com/2025/biz/news/paramount-skydance-layoffs-start-1236561992/ - content
77/496 | Scraped url(3085): https://variety.com/2025/biz/news/paramount-skydance-layoffs-start-1236561992/
https://www.barchart.com/story/news/35709247/amd-stock-at-record-highs-buy-sell-or-hold-before-q3-earnings - content
78/496 | Scraped url(0): https://www.barchart.com/story/news/35709247/amd-stock-at-record-highs-buy-sell-or-hold-before-q3-earnings
https://www.theregister.com/2025/10/27/signal_ceo_meredith_whittaker_aws_dependency/ - content
79/496 | Scraped url(0): https://www.theregister.com/2025/10/27/signal_ceo_meredith_whittaker_aws_dependency/
https://www.forbes.com/sites/bryanpenprase/2025/10/27/mbzuai--building-humanitys-symbiotic-relationship-with-ai/ - content
80/496 | Scraped url(8356): https://www.forbes.com/sites/bryanpenprase/2025/10/27/mbzuai--building-humanitys-symbiotic-relationship-with-ai/
https://www.forbes.com/sites/markledain/2025/10/27/the-ai-race-is-an-energy-race-and-regions-with-nat-gas-are-winning/ - content
81/496 | Scraped url(5337): https://www.forbes.com/sites/markledain/2025/10/27/the-ai-race-is-an-energy-race-and-regions-with-nat-gas-are-winning/
81/496 | Sleeping for 0.6975648867254898s
https://biztoc.com/x/6422f5d779bbd639 - content
82/496 | Scraped url(285): https://biztoc.com/x/6422f5d779bbd639
https://www.barchart.com/story/news/35707947/ceo-clay-magouyrk-is-selling-oracle-stock-should-you - content
83/496 | Scraped url(0): https://www.barchart.com/story/news/35707947/ceo-clay-magouyrk-is-selling-oracle-stock-should-you
https://www.fark.com/comments/13858574/Dave-Ramsey-explains-why-so-many-teachers-keep-becoming-millionaires-Dave-Ramsey-apparently-knows-different-teachers-than-subby-does - content
84/496 | Scraped url(18766): https://www.fark.com/comments/13858574/Dave-Ramsey-explains-why-so-many-teachers-keep-becoming-millionaires-Dave-Ramsey-apparently-knows-different-teachers-than-subby-does
https://www.thestreet.com/video/whats-really-driving-the-stock-market-this-week - content
85/496 | Scraped url(43): https://www.thestreet.com/video/whats-really-driving-the-stock-market-this-week
https://www.globenewswire.com/news-release/2025/10/27/3174918/0/en/AMD-Powers-U-S-Sovereign-AI-Factory-Supercomputers-Accelerating-an-Open-American-AI-Stack.html - content
86/496 | Scraped url(14669): https://www.globenewswire.com/news-release/2025/10/27/3174918/0/en/AMD-Powers-U-S-Sovereign-AI-Factory-Supercomputers-Accelerating-an-Open-American-AI-Stack.html
https://finance.yahoo.com/news/exclusive-germanys-sap-mulls-bid-185132952.html - content
87/496 | Scraped url(0): https://finance.yahoo.com/news/exclusive-germanys-sap-mulls-bid-185132952.html
https://finance.yahoo.com/news/analyst-bullish-oracle-corp-orcl-184955145.html - content
88/496 | Scraped url(0): https://finance.yahoo.com/news/analyst-bullish-oracle-corp-orcl-184955145.html
https://www.cnbc.com/2025/10/27/ai-is-driving-huge-productivity-gains-for-large-companies-while-small-companies-get-left-behind.html - content
89/496 | Scraped url(160): https://www.cnbc.com/2025/10/27/ai-is-driving-huge-productivity-gains-for-large-companies-while-small-companies-get-left-behind.html
https://pypi.org/project/pulumi-oci/3.10.0a1761588865/ - content
90/496 | Scraped url(21963): https://pypi.org/project/pulumi-oci/3.10.0a1761588865/
https://fortune.com/2025/10/27/marc-benioff-san-francisco-dreamforce-salesforce-national-guard-controversy/ - content
91/496 | Scraped url(11735): https://fortune.com/2025/10/27/marc-benioff-san-francisco-dreamforce-salesforce-national-guard-controversy/
91/496 | Sleeping for 0.6035900741318608s
https://finance.yahoo.com/news/media-missed-message-benioff-clarifies-183402360.html - content
92/496 | Scraped url(0): https://finance.yahoo.com/news/media-missed-message-benioff-clarifies-183402360.html
https://www.forbes.com/sites/sindiswamabunda/2025/10/27/how-africas-formula-1-ambitions-are-fuelling-a-new-era-of-sports-investment/ - content

,author,title,description,url,url_to_image,published_at_utc,content_truncated,source_id,source_name,url_domain,content_full,content_size
0,benzinga.com,Oracle Unveils Digital Assets Platform To Powe...,Oracle Corp (NYSE:ORCL) announced plans to lau...,https://biztoc.com/x/351b2b78fb9ac1ff,https://biztoc.com/cdn/351b2b78fb9ac1ff_s.webp,2025-10-28 16:20:33,Oracle Corp (NYSE:ORCL) announced plans to lau...,None,Biztoc.com,biztoc.com,Oracle Corp (NYSE:ORCL) announced plans to lau...,288
1,info@thehackernews.com (The Hacker News),Researchers Expose GhostCall and GhostHire: Bl...,Threat actors tied to North Korea have been ob...,https://thehackernews.com/2025/10/researchers-...,https://blogger.googleusercontent.com/img/b/R2...,2025-10-28 16:12:00,Threat actors tied to North Korea have been ob...,None,Internet,thehackernews.com,Threat actors tied to North Korea have been ob...,7616
2,Business Wire,Hexagon and Management Controls Deliver Real-T...,New integration advances digital project contr...,https://financialpost.com/pmn/business-wire-ne...,None,2025-10-28 16:07:04,New integration advances digital project contr...,financial-post,Financial Post,financialpost.com,,0
3,Syeda Seirut Javed,Jim Cramer Says “NVIDIA is the Most Supply-Con...,NVIDIA Corporation (NASDAQ:NVDA) is one of the...,https://finance.yahoo.com/news/jim-cramer-says...,https://s.yimg.com/ny/api/res/1.2/j4O.v5gpguu....,2025-10-28 16:02:55,NVIDIA Corporation (NASDAQ:NVDA) is one of the...,None,Yahoo Entertainment,finance.yahoo.com,,0
4,Matthew Strauss,Animal Collective’s Geologist Announces Debut ...,“Tonic” leads January’s Can I Get a Pack of Ca...,https://pitchfork.com/news/animal-collective-g...,https://media.pitchfork.com/photos/6900e85d5f0...,2025-10-28 16:01:02,"Brian Ross Weitz, the Animal Collective musici...",None,Pitchfork,pitchfork.com,"Brian Ross Weitz, theAnimal Collectivemusician...",2403
5,Fred Lambert,"Elon Musk is not leaving Tesla, but he is usin...",Elon Musk and Tesla’s board keep repeating the...,http://electrek.co/2025/10/28/elon-musk-not-le...,https://i0.wp.com/electrek.co/wp-content/uploa...,2025-10-28 15:44:26,Elon Musk and Tesla’s board keep repeating the...,None,Electrek,electrek.co,Elon Musk and Tesla’s board keep repeating the...,6994
6,Author: Cliff Joseph,VirtualBox review: Supports Windows on M-serie...,Macworld\n\n\n\r\n\n\n\nAt a glance\r\nExpert'...,https://www.macworld.com/article/2949071/virtu...,https://www.macworld.com/wp-content/uploads/20...,2025-10-28 15:28:05,Skip to contentType your search and hit enter\...,None,Macworld,www.macworld.com,When you purchase through links in our article...,7346
7,Daniel Howley,Microsoft to report Q1 earnings following new ...,Microsoft will announce its first quarter earn...,https://finance.yahoo.com/news/microsoft-to-re...,https://s.yimg.com/ny/api/res/1.2/6hrTce0mQfjD...,2025-10-28 15:19:33,Microsoft (MSFT) is scheduled to report its fi...,None,Yahoo Entertainment,finance.yahoo.com,,0
8,Laura Bratton,Big Tech has to 'walk the line' with AI spendi...,Any pullback in AI spending from Big Tech comp...,https://finance.yahoo.com/news/big-tech-has-to...,https://s.yimg.com/ny/api/res/1.2/RoQYwZwHGFV0...,2025-10-28 15:19:04,Tech giants are expected to have continued ram...,None,Yahoo Entertainment,finance.yahoo.com,,0
9,"Dan Runkevicius, Senior Contributor, \n Dan Ru...",AI is More Than Stock Market. It’s Economic ‘S...,Stock market and economic growth are hanging b...,https://www.forbes.com/sites/danrunkevicius/20...,https://imageio.forbes.com/specials-images/ima...,2025-10-28 15:16:07,NurPhoto via Getty Images\r\nTheres a lot of t...,None,Forbes,www.forbes.com,"ByDan Runkevicius, Senior Contributor. There’s...",2872
10,benzinga.com,Lawrence J. Ellison Sees Potential Growth And ...,"On October 28, Ellison, Executive Chairman at ...",https://biztoc.com/x/5093f82c166a71e3,https://biztoc.com/cdn/5093f82c166a71e3_s.webp,2025-10-28 15:13:56,"On October 28, Ellison, Executive Chairman at ...",None,Biztoc.com,biztoc.com,"On October 28, Ellison, Executive Chairman at ...",280
11,Noah Weidner,Stock Market Today: U.S. Stocks Rise After Pay...,This live blog is refreshed periodically throu...,https://www.thestreet.com/markets/stock-market...,https://media.zenfs.com/en/thestreet_881/0fb41...,2025-10-28 15:10:48,This live blog is refreshed periodically throu...,None,TheStreet,www.thestreet.com,Please enable JS and disable any ad blocker,43
12,David Corn,Another Big Reason to Worry About Bari Weiss’ ...,A version of the below article first appeared ...,https://www.motherjones.com/politics/2025/10/b...,https://www.motherjones.com/wp-content/uploads...,2025-10-28 15:07:41,Mother Jones illustratuion; Alberto E. Tamargo...,None,Mother Jones,www.motherjones.com,Mother Jones illustration; Alberto E. Tamargo/...,14250
13,finance.yahoo.com,Monness Maintains Neutral Stance on Oracle (OR...,Oracle Corporation (NYSE:ORCL) is one of the M...,https://biztoc.com/x/0df2ec0da4a4f484,https://biztoc.com/cdn/0df2ec0da4a4f484_s.webp,2025-10-28 15:03:36,Oracle Corporation (NYSE:ORCL) is one of the M...,None,Biztoc.com,biztoc.com,Oracle Corporation (NYSE:ORCL) is one of the M...,289
14,None,"(Business Journal, 10/27) f⒤荵若ォ若オ鴻 ...","(Business Journal, 10/27) f⒤荵若ォ若オ鴻ィッ礇湛筝㊤絨＜七 c荵...",http://www.st.ryukoku.ac.jp/~kjm/security/memo...,None,2025-10-28 15:00:00,Last modified: Wed Oct 29 16:55:53 2025\r\n +0...,None,Ryukoku.ac.jp,www.st.ryukoku.ac.jp,Last modified: Wed Oct 29 18:20:08 2025+0900 (...,23495
15,finance.yahoo.com,"Analysts revamp Oracle stock forecast, with ne...",Oracle may have joined the artificial intellig...,https://biztoc.com/x/616afdeaea9d0199,https://biztoc.com/cdn/616afdeaea9d0199_s.webp,2025-10-28 14:52:15,Oracle may have joined the artificial intellig...,None,Biztoc.com,biztoc.com,Oracle may have joined the artificial intellig...,284
16,Bob Karr,Wedbush Raises PT on Advanced Micro Devices (A...,"Advanced Micro Devices, Inc. (NASDAQ:AMD) is o...",https://finance.yahoo.com/news/wedbush-raises-...,https://s.yimg.com/ny/api/res/1.2/urMM2VzBkSHT...,2025-10-28 14:46:50,"Advanced Micro Devices, Inc. (NASDAQ:AMD) is o...",None,Yahoo Entertainment,finance.yahoo.com,,0
17,Bob Karr,Monness Maintains Neutral Stance on Oracle (OR...,Oracle Corporation (NYSE:ORCL) is one of the M...,https://finance.yahoo.com/news/monness-maintai...,https://s.yimg.com/ny/api/res/1.2/1zuBrjMipYtG...,2025-10-28 14:46:47,Oracle Corporation (NYSE:ORCL) is one of the M...,None,Yahoo Entertainment,finance.yahoo.com,,0
18,Vuk Zdinjak,"Analysts revamp Oracle stock forecast, with ne...",Oracle may have joined the artificial intellig...,https://www.thestreet.com/investing/stocks/ana...,https://media.zenfs.com/en/thestreet_881/ed3f2...,2025-10-28 14:37:00,Oracle may have joined the artificial intellig...,None,TheStreet,www.thestreet.com,Please enable JS and disable any ad blocker,43
19,tmohamed@businessinsider.com (Theron Mohamed),The world's 10 richest people are $500 billion...,The 10 wealthiest people on the planet are joi...,https://www.businessinsider.com/10-richest-peo...,https://i.insider.com/6900b3d4599d46a4ccc0f6e9...,2025-10-28 14:35:02,The uber-rich are only getting richer as inves...,business-insider,Business Insider,www.businessinsider.com,"Every time Theron publishes a story, you’ll ge...",2646

## Pushing to RAW Schema

In [12]:
def preprocess_dataframe(df):
    """
    Creating the primary key hash & ingested_at value.
    """
    df = df.copy()
    df["article_id"] = df.apply(
        lambda row: hashlib.sha1(f"{row['url']}_{row['published_at_utc']}".encode()).hexdigest(),
        axis=1
    )
    # "ingested_at" is re-written when pushing to prod raw using SQL
    df["ingested_at"] = pd.Timestamp.now(tz="UTC").tz_localize(None)
    config_run = get_config_run(GLOBAL_RUN_NAME)
    df["entity_name"] = config_run["entity_name"]
    expected_cols = [
        "entity_name",
        "article_id","author","title","description","url","url_to_image",
        "published_at_utc","content_truncated","source_id","source_name",
        "url_domain","content_full","content_size","ingested_at"
    ]
    return df[expected_cols]

df = preprocess_dataframe(df)
df.head(3)

,entity_name,article_id,author,title,description,url,url_to_image,published_at_utc,content_truncated,source_id,source_name,url_domain,content_full,content_size,ingested_at
0,Oracle,754ec79b124aadd689be66e83da05b7b492366ba,benzinga.com,Oracle Unveils Digital Assets Platform To Powe...,Oracle Corp (NYSE:ORCL) announced plans to lau...,https://biztoc.com/x/351b2b78fb9ac1ff,https://biztoc.com/cdn/351b2b78fb9ac1ff_s.webp,2025-10-28 16:20:33,Oracle Corp (NYSE:ORCL) announced plans to lau...,None,Biztoc.com,biztoc.com,Oracle Corp (NYSE:ORCL) announced plans to lau...,288,2025-10-29 16:40:51.383325
1,Oracle,1b0d7a28627e73d8385cb5e5b4cfa75d8a153929,info@thehackernews.com (The Hacker News),Researchers Expose GhostCall and GhostHire: Bl...,Threat actors tied to North Korea have been ob...,https://thehackernews.com/2025/10/researchers-...,https://blogger.googleusercontent.com/img/b/R2...,2025-10-28 16:12:00,Threat actors tied to North Korea have been ob...,None,Internet,thehackernews.com,Threat actors tied to North Korea have been ob...,7616,2025-10-29 16:40:51.383325
2,Oracle,17637e32616172d34199b00b2d4ad05cfd6295e1,Business Wire,Hexagon and Management Controls Deliver Real-T...,New integration advances digital project contr...,https://financialpost.com/pmn/business-wire-ne...,None,2025-10-28 16:07:04,New integration advances digital project contr...,financial-post,Financial Post,financialpost.com,,0,2025-10-29 16:40:51.383325

In [13]:
# Locally save to CSV for debugging
df.to_csv("g:/Signal-Extraction/src/1_ingestion/local_test/debug_news_api_output.csv", index=False)

In [14]:
# Creating a Temp view & table - Session Scoped
def create_temp_table_from_df(df, temp_table="NEWS_ARTICLES_TEMP"):
    """
    Creating a Temp Table (Session Scoped), can be used within the notebook.
    """

    conn = get_snowlfake_conn(schema_name="RAW")
    cur = conn.cursor()

    try:
        # Drop old temp table if exists
        cur.execute(f"DROP TABLE IF EXISTS {temp_table}")

        # Write dataframe to a temp table
        success, nchunks, nrows, _ = write_pandas(
            conn, 
            df, 
            table_name=temp_table, 
            auto_create_table=True, 
            overwrite=True, 
            quote_identifiers=False,
            use_logical_type=True
        )

        print(f"[INFO] Temp table created: {temp_table}, Rows inserted: {nrows}")
    
    finally:
        cur.close()
        conn.close()
    
create_temp_table_from_df(df, temp_table="NEWS_ARTICLES_TEMP")

DatabaseError: 250001 (08001): Failed to connect to DB: CYWCXZB-EPC46775.snowflakecomputing.com:443. Incorrect username or password was specified.

In [ ]:
SELECT * FROM NEWS_ARTICLES_TEMP LIMIT 3;

In [ ]:
CREATE TABLE IF NOT EXISTS SIGNAL_EXTRACTION_DB.RAW.NEWS_ARTICLES (
    article_id STRING PRIMARY KEY,
    author STRING,
    title STRING,
    description STRING,
    url STRING,
    url_to_image STRING,
    published_at_utc TIMESTAMP_NTZ,
    content_truncated STRING,
    source_id STRING,
    source_name STRING,
    url_domain STRING,
    content_full STRING,
    content_size NUMBER,
    ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

In [ ]:
// Still update if aritcle_id already exists, incase the latest ingestion has some updated fields or values.

MERGE INTO SIGNAL_EXTRACTION_DB.RAW.NEWS_ARTICLES AS target
USING NEWS_ARTICLES_TEMP AS source
ON target.article_id = source.article_id
WHEN MATCHED THEN UPDATE SET
    -- target.entity_name       = source.entity_name,
    target.author            = source.author,
    target.title             = source.title,
    target.description       = source.description,
    target.url               = source.url,
    target.url_to_image      = source.url_to_image,
    target.published_at_utc  = source.published_at_utc,
    target.content_truncated = source.content_truncated,
    target.source_id         = source.source_id,
    target.source_name       = source.source_name,
    target.url_domain        = source.url_domain,
    target.content_full      = source.content_full,
    target.content_size      = source.content_size,
    target.ingested_at       = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        -- entity_name,
        article_id, author, title, description, url,
        url_to_image,published_at_utc, content_truncated,
        source_id, source_name, url_domain, 
        content_full, content_size, ingested_at
    )
    VALUES (
        -- source.entity_name,
        source.article_id, source.author, source.title, 
        source.description, source.url,
        source.url_to_image, source.published_at_utc,
        source.content_truncated, source.source_id,
        source.source_name, source.url_domain,
        source.content_full, source.content_size, CURRENT_TIMESTAMP
    );

In [ ]:
SELECT * FROM SIGNAL_EXTRACTION_DB.RAW.NEWS_ARTICLES LIMIT 3;

## Future Developement

In [ ]:
-- TODO: Future, map all the article_id s to different entities like dependent market news and others.

-- insert_sql = """
-- INSERT INTO RAW.ARTICLE_ENTITY_MAP (article_id, q_value, entity_name)
-- SELECT s.article_id, s.q_value, s.entity_name
-- FROM NEWS_ARTICLES_TEMP s
-- WHERE NOT EXISTS (
--     SELECT 1
--     FROM RAW.ARTICLE_ENTITY_MAP m
--     WHERE m.article_id  = s.article_id
--       AND m.q_value     = s.q_value
--       AND m.entity_name = s.entity_name
-- );
-- """